package requestid

import (
	"context"

	"github.com/sirupsen/logrus"
)

// NewLogger returns a new FieldLogger containing the RequestID generated by the middleware
func NewLogger(requestID string, ancestorLog logrus.FieldLogger) logrus.FieldLogger {
	var logger logrus.FieldLogger = logrus.StandardLogger()
	if ancestorLog != nil {
		logger = ancestorLog
	}

	return logger.WithField(string(ContextKeyRequestID), requestID)
}

// NewLoggerFromContext returns a new FieldLogger from a context
// which contains the RequestID generated by the middleware
func NewLoggerFromContext(ctx context.Context, ancestorLog logrus.FieldLogger) logrus.FieldLogger {
	return NewLogger(GetID(ctx), ancestorLog)
}
